// lib/firebase_options.dart
// File generated by FlutterFire CLI or manually.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError();
      case TargetPlatform.windows:
        throw UnsupportedError('Windows not supported yet');
      case TargetPlatform.linux:
        throw UnsupportedError('Linux not supported yet');
      default:
        throw UnsupportedError('Unsupported platform');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB8eXKfExV-DWOJ5a3Zd_NyOguwtPAUr0',
    appId: '1:559736666048:web:e541e3de7d9c96e671fa25',
    messagingSenderId: '559736666048',
    projectId: 'expense-tracking-54dd5',
    authDomain: 'expense-tracking-54dd5.firebaseapp.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvbAxp2wv7gm5P68PKEjEvaU20A2MVQ3k',
    appId: '1:559736666048:android:dc55d819a6f1cffb71fa25',
    messagingSenderId: 'expense tracker',
    projectId: 'expense-tracking-54dd5',
    storageBucket: 'expense-tracking-54dd5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn49tg3MsN9x23qpFZ_OYqI5jpTNSmrfk',
    appId: '1:559736666048:ios:f5ac5ffc3ef3b6db71fa25',
    messagingSenderId: '559736666048',
    projectId: 'expense-tracking-54dd5',
    storageBucket: 'expense-tracking-54dd5.firebasestorage.app',
    iosBundleId:
        'com.favlinks.expensetracking', // change if your bundle ID is different
  );
}
